export declare enum RawKeys {
    LeftMouseBtn = 1,//Left mouse button
    RightMouseBtn = 2,//Right mouse button
    CtrlBrkPrcs = 3,//Control-break processing
    MidMouseBtn = 4,//Middle mouse button
    ThumbForward = 5,//Thumb button back on mouse aka X1
    ThumbBack = 6,//Thumb button forward on mouse aka X2
    BackSpace = 8,//Backspace key
    Tab = 9,//Tab key
    Clear = 12,//Clear key
    Enter = 13,//Enter or Return key
    Shift = 16,//Shift key
    Control = 17,//Ctrl key
    Alt = 18,//Alt key
    Pause = 19,//Pause key
    CapsLock = 20,//Caps lock key
    Kana = 21,//Kana input mode
    Hangeul = 21,//Hangeul input mode
    Hangul = 21,//Hangul input mode
    Junju = 23,//Junja input method
    Final = 24,//Final input method
    Hanja = 25,//Hanja input method
    Kanji = 25,//Kanji input method
    Escape = 27,//Esc key
    Convert = 28,//IME convert
    NonConvert = 29,//IME Non convert
    Accept = 30,//IME accept
    ModeChange = 31,//IME mode change
    Space = 32,//Space bar
    PageUp = 33,//Page up key
    PageDown = 34,//Page down key
    End = 35,//End key
    Home = 36,//Home key
    LeftArrow = 37,//Left arrow key
    UpArrow = 38,//Up arrow key
    RightArrow = 39,//Right arrow key
    DownArrow = 40,//Down arrow key
    Select = 41,//Select key
    Print = 42,//Print key
    Execute = 43,//Execute key
    PrintScreen = 44,//Print screen key
    Inser = 45,//Insert key
    Delete = 46,//Delete key
    Help = 47,//Help key
    Num0 = 48,//Top row 0 key (Matches '0')
    Num1 = 49,//Top row 1 key (Matches '1')
    Num2 = 50,//Top row 2 key (Matches '2')
    Num3 = 51,//Top row 3 key (Matches '3')
    Num4 = 52,//Top row 4 key (Matches '4')
    Num5 = 53,//Top row 5 key (Matches '5')
    Num6 = 54,//Top row 6 key (Matches '6')
    Num7 = 55,//Top row 7 key (Matches '7')
    Num8 = 56,//Top row 8 key (Matches '8')
    Num9 = 57,//Top row 9 key (Matches '9')
    A = 65,//A key (Matches 'A')
    B = 66,//B key (Matches 'B')
    C = 67,//C key (Matches 'C')
    D = 68,//D key (Matches 'D')
    E = 69,//E key (Matches 'E')
    F = 70,//F key (Matches 'F')
    G = 71,//G key (Matches 'G')
    H = 72,//H key (Matches 'H')
    I = 73,//I key (Matches 'I')
    J = 74,//J key (Matches 'J')
    K = 75,//K key (Matches 'K')
    L = 76,//L key (Matches 'L')
    M = 77,//M key (Matches 'M')
    N = 78,//N key (Matches 'N')
    O = 79,//O key (Matches 'O')
    P = 80,//P key (Matches 'P')
    Q = 81,//Q key (Matches 'Q')
    R = 82,//R key (Matches 'R')
    S = 83,//S key (Matches 'S')
    T = 84,//T key (Matches 'T')
    U = 85,//U key (Matches 'U')
    V = 86,//V key (Matches 'V')
    W = 87,//W key (Matches 'W')
    X = 88,//X key (Matches 'X')
    Y = 89,//Y key (Matches 'Y')
    Z = 90,//Z key (Matches 'Z')
    LeftWin = 91,//Left windows key
    RightWin = 92,//Right windows key
    Apps = 93,//Applications key
    Sleep = 95,//Computer sleep key
    Numpad0 = 96,//Numpad 0
    Numpad1 = 97,//Numpad 1
    Numpad2 = 98,//Numpad 2
    Numpad3 = 99,//Numpad 3
    Numpad4 = 100,//Numpad 4
    Numpad5 = 101,//Numpad 5
    Numpad6 = 102,//Numpad 6
    Numpad7 = 103,//Numpad 7
    Numpad8 = 104,//Numpad 8
    Numpad9 = 105,//Numpad 9
    Multiply = 106,//Multiply key
    Add = 107,//Add key
    Separator = 108,//Separator key
    Subtract = 109,//Subtract key
    Decimal = 110,//Decimal key
    Divide = 111,//Divide key
    F1 = 112,//F1
    F2 = 113,//F2
    F3 = 114,//F3
    F4 = 115,//F4
    F5 = 116,//F5
    F6 = 117,//F6
    F7 = 118,//F7
    F8 = 119,//F8
    F9 = 120,//F9
    F10 = 121,//F10
    F11 = 122,//F11
    F12 = 123,//F12
    F13 = 124,//F13
    F14 = 125,//F14
    F15 = 126,//F15
    F16 = 127,//F16
    F17 = 128,//F17
    F18 = 129,//F18
    F19 = 130,//F19
    F20 = 131,//F20
    F21 = 132,//F21
    F22 = 133,//F22
    F23 = 134,//F23
    F24 = 135,//F24
    NavigationView = 136,//reserved
    NavigationMenu = 137,//reserved
    NavigationUp = 138,//reserved
    NavigationDown = 139,//reserved
    NavigationLeft = 140,//reserved
    NavigationRight = 141,//reserved
    NavigationAccept = 142,//reserved
    NavigationCancel = 143,//reserved
    NumLock = 144,//Num lock key
    ScrollLock = 145,//Scroll lock key
    NumpadEqual = 146,//Numpad =
    FJ_Jisho = 146,//Dictionary key
    FJ_Masshou = 147,//Unregister word key
    FJ_Touroku = 148,//Register word key
    FJ_Loya = 149,//Left OYAYUBI key
    FJ_Roya = 150,//Right OYAYUBI key
    LeftShift = 160,//Left shift key
    RightShift = 161,//Right shift key
    LeftCtrl = 162,//Left control key
    RightCtrl = 163,//Right control key
    LeftMenu = 164,//Left menu key
    RightMenu = 165,//Right menu
    BrowserBack = 166,//Browser back button
    BrowserForward = 167,//Browser forward button
    BrowserRefresh = 168,//Browser refresh button
    BrowserStop = 169,//Browser stop button
    BrowserSearch = 170,//Browser search button
    BrowserFavorites = 171,//Browser favorites button
    BrowserHome = 172,//Browser home button
    VolumeMute = 173,//Volume mute button
    VolumeDown = 174,//Volume down button
    VolumeUp = 175,//Volume up button
    NextTrack = 176,//Next track media button
    PrevTrack = 177,//Previous track media button
    Stop = 178,//Stop media button
    PlayPause = 179,//Play/pause media button
    Mail = 180,//Launch mail button
    MediaSelect = 181,//Launch media select button
    App1 = 182,//Launch app 1 button
    App2 = 183,//Launch app 2 button
    OEM1 = 186,//;: key for US or misc keys for others
    Plus = 187,//Plus key
    Comma = 188,//Comma key
    Minus = 189,//Minus key
    Period = 190,//Period key
    OEM2 = 191,//? for US or misc keys for others
    OEM3 = 192,//~ for US or misc keys for others
    Gamepad_A = 195,//Gamepad A button
    Gamepad_B = 196,//Gamepad B button
    Gamepad_X = 197,//Gamepad X button
    Gamepad_Y = 198,//Gamepad Y button
    GamepadRightBumper = 199,//Gamepad right bumper
    GamepadLeftBumper = 200,//Gamepad left bumper
    GamepadLeftTrigger = 201,//Gamepad left trigger
    GamepadRightTrigger = 202,//Gamepad right trigger
    GamepadDPadUp = 203,//Gamepad DPad up
    GamepadDPadDown = 204,//Gamepad DPad down
    GamepadDPadLeft = 205,//Gamepad DPad left
    GamepadDPadRight = 206,//Gamepad DPad right
    GamepadMenu = 207,//Gamepad menu button
    GamepadView = 208,//Gamepad view button
    GamepadLeftStickBtn = 209,//Gamepad left stick button
    GamepadRightStickBtn = 210,//Gamepad right stick button
    GamepadLeftStickUp = 211,//Gamepad left stick up
    GamepadLeftStickDown = 212,//Gamepad left stick down
    GamepadLeftStickRight = 213,//Gamepad left stick right
    GamepadLeftStickLeft = 214,//Gamepad left stick left
    GamepadRightStickUp = 215,//Gamepad right stick up
    GamepadRightStickDown = 216,//Gamepad right stick down
    GamepadRightStickRight = 217,//Gamepad right stick right
    GamepadRightStickLeft = 218,//Gamepad right stick left
    OEM4 = 219,//[ for US or misc keys for others
    OEM5 = 220,//\ for US or misc keys for others
    OEM6 = 221,//] for US or misc keys for others
    OEM7 = 222,//' for US or misc keys for others
    OEM8 = 223,//Misc keys for others
    OEMAX = 225,//AX key on Japanese AX keyboard
    OEM102 = 226,//"<>" or "\|" on RT 102-key keyboard
    ICOHelp = 227,//Help key on ICO
    ICO00 = 228,//00 key on ICO
    ProcessKey = 229,//Process key input method
    OEMCLEAR = 230,//OEM specific
    Packet = 231,//IDK man try to google it
    OEMReset = 233,//OEM reset button
    OEMJump = 234,//OEM jump button
    OEMPA1 = 235,//OEM PA1 button
    OEMPA2 = 236,//OEM PA2 button
    OEMPA3 = 237,//OEM PA3 button
    OEMWSCtrl = 238,//OEM WS Control button
    OEMCusel = 239,//OEM CUSEL button
    OEMAttn = 240,//OEM ATTN button
    OEMFinish = 241,//OEM finish button
    OEMCopy = 242,//OEM copy button
    OEMAuto = 243,//OEM auto button
    OEMEnlw = 244,//OEM ENLW
    OEMBackTab = 245,//OEM back tab
    Attn = 246,//Attn
    CrSel = 247,//CrSel
    ExSel = 248,//ExSel
    EraseEOF = 249,//Erase EOF key
    Play = 250,//Play key
    Zoom = 251,//Zoom key
    NoName = 252,//No name
    PA1 = 253,//PA1 key
    OEMClear = 254
}
