import { Vector3 } from "../common/utils/Vector";
import { CommonBaseEntity } from "./entities/CommonBaseEntity";
import { CommonPed } from "./entities/CommonPed";
import type { CommonVehicle } from "./entities/CommonVehicle";
import { VehicleSeat } from "./enums/VehicleSeat";
import { IHandle } from "./entities/IHandle";
export declare class CommonTasks {
    protected ped: IHandle;
    constructor(ped: IHandle | null);
    achieveHeading(heading: number, timeout?: number): void;
    blockTemporaryEvents(block?: boolean): void;
    aimAt(target: CommonBaseEntity | Vector3, duration: number): void;
    arrest(ped: CommonPed): void;
    jump(): void;
    climb(): void;
    cruiseWithVehicle(vehicle: CommonVehicle, speed: number, drivingStyle?: number): void;
    enterAnyVehicle(seat?: VehicleSeat, timeout?: number, speed?: number, flag?: number): void;
    static everyoneLeaveVehicle(vehicle: CommonVehicle): void;
    fightAgainst(target: CommonPed, duration?: number): void;
    fightAgainstHatedTargets(radius: number, duration?: number): void;
    fleeFrom(pedOrPosition: CommonPed | Vector3, distance?: number, duration?: number, fleeType?: number, fleeSpeed?: number, fleeFrom?: IHandle): void;
    goTo(position: Vector3, ignorePaths?: boolean, timeout?: number, speed?: number, targetHeading?: number, distanceToSlide?: number, flags?: number): void;
    goToEntity(target: CommonBaseEntity, offset?: Vector3, timeout?: number): void;
    guardCurrentPosition(): void;
    handsUp(duration: number): void;
    lookAt(targetOrPosition: CommonBaseEntity | Vector3, duration?: number): void;
    playAnimation(animDict: string, animName: string, blendInSpeed: number, blendOutSpeed: number, duration: number, playbackRate: number, animFlags: number, ikFlags?: number): Promise<void>;
    reloadWeapon(): void;
    shootAt(targetOrPosition: IHandle | Vector3, duration?: number, pattern?: number, affectCockedState?: boolean): void;
    shuffleToNextVehicleSeat(vehicle: CommonVehicle): void;
    slideTo(position: Vector3, heading: number, duration?: number): void;
    standStill(duration: number): void;
    vehicleShootAtPed(target: CommonPed): void;
    wait(duration: number): void;
    wanderAround(position?: Vector3, radius?: number): void;
    warpIntoVehicle(vehicle: CommonVehicle, seat: VehicleSeat): void;
    warpOutOfVehicle(vehicle: CommonVehicle, flags: number): void;
    isPlayingAnim(dict: string, anim: string, taskFlag?: number): boolean;
    clearAll(): void;
    clearAllImmediately(): void;
    clearLookAt(): void;
    clearSecondary(): void;
    clearAnimation(animDict: string, animName: string): void;
}
