import { AmmoModel } from "./models/AmmoModel";
const AMMO_22 = new AmmoModel("AMMO_22");
const AMMO_22_TRANQUILIZER = new AmmoModel("AMMO_22_TRANQUILIZER");
const AMMO_ARROW = new AmmoModel("AMMO_ARROW");
const AMMO_ARROW_CONFUSION = new AmmoModel("AMMO_ARROW_CONFUSION");
const AMMO_ARROW_DISORIENT = new AmmoModel("AMMO_ARROW_DISORIENT");
const AMMO_ARROW_DRAIN = new AmmoModel("AMMO_ARROW_DRAIN");
const AMMO_ARROW_DYNAMITE = new AmmoModel("AMMO_ARROW_DYNAMITE");
const AMMO_ARROW_FIRE = new AmmoModel("AMMO_ARROW_FIRE");
const AMMO_ARROW_IMPROVED = new AmmoModel("AMMO_ARROW_IMPROVED");
const AMMO_ARROW_POISON = new AmmoModel("AMMO_ARROW_POISON");
const AMMO_ARROW_SMALL_GAME = new AmmoModel("AMMO_ARROW_SMALL_GAME");
const AMMO_ARROW_TRACKING = new AmmoModel("AMMO_ARROW_TRACKING");
const AMMO_ARROW_TRAIL = new AmmoModel("AMMO_ARROW_TRAIL");
const AMMO_ARROW_WOUND = new AmmoModel("AMMO_ARROW_WOUND");
const AMMO_BOLAS = new AmmoModel("AMMO_BOLAS");
const AMMO_BOLAS_HAWKMOTH = new AmmoModel("AMMO_BOLAS_HAWKMOTH");
const AMMO_BOLAS_INTERTWINED = new AmmoModel("AMMO_BOLAS_INTERTWINED");
const AMMO_BOLAS_IRONSPIKED = new AmmoModel("AMMO_BOLAS_IRONSPIKED");
const AMMO_CANNON = new AmmoModel("AMMO_CANNON");
const AMMO_DYNAMITE = new AmmoModel("AMMO_DYNAMITE");
const AMMO_DYNAMITE_VOLATILE = new AmmoModel("AMMO_DYNAMITE_VOLATILE");
const AMMO_HATCHET = new AmmoModel("AMMO_HATCHET");
const AMMO_HATCHET_ANCIENT = new AmmoModel("AMMO_HATCHET_ANCIENT");
const AMMO_HATCHET_CLEAVER = new AmmoModel("AMMO_HATCHET_CLEAVER");
const AMMO_HATCHET_DOUBLE_BIT = new AmmoModel("AMMO_HATCHET_DOUBLE_BIT");
const AMMO_HATCHET_DOUBLE_BIT_RUSTED = new AmmoModel("AMMO_HATCHET_DOUBLE_BIT_RUSTED");
const AMMO_HATCHET_HEWING = new AmmoModel("AMMO_HATCHET_HEWING");
const AMMO_HATCHET_HUNTER = new AmmoModel("AMMO_HATCHET_HUNTER");
const AMMO_HATCHET_HUNTER_RUSTED = new AmmoModel("AMMO_HATCHET_HUNTER_RUSTED");
const AMMO_HATCHET_VIKING = new AmmoModel("AMMO_HATCHET_VIKING");
const AMMO_LASSO = new AmmoModel("AMMO_LASSO");
const AMMO_LASSO_REINFORCED = new AmmoModel("AMMO_LASSO_REINFORCED");
const AMMO_MOLOTOV = new AmmoModel("AMMO_MOLOTOV");
const AMMO_MOLOTOV_VOLATILE = new AmmoModel("AMMO_MOLOTOV_VOLATILE");
const AMMO_MOONSHINEJUG = new AmmoModel("AMMO_MOONSHINEJUG");
const AMMO_MOONSHINEJUG_MP = new AmmoModel("AMMO_MOONSHINEJUG_MP");
const AMMO_PISTOL = new AmmoModel("AMMO_PISTOL");
const AMMO_PISTOL_EXPRESS = new AmmoModel("AMMO_PISTOL_EXPRESS");
const AMMO_PISTOL_EXPRESS_EXPLOSIVE = new AmmoModel("AMMO_PISTOL_EXPRESS_EXPLOSIVE");
const AMMO_PISTOL_HIGH_VELOCITY = new AmmoModel("AMMO_PISTOL_HIGH_VELOCITY");
const AMMO_PISTOL_SPLIT_POINT = new AmmoModel("AMMO_PISTOL_SPLIT_POINT");
const AMMO_POISONBOTTLE = new AmmoModel("AMMO_POISONBOTTLE");
const AMMO_REPEATER = new AmmoModel("AMMO_REPEATER");
const AMMO_REPEATER_EXPRESS = new AmmoModel("AMMO_REPEATER_EXPRESS");
const AMMO_REPEATER_EXPRESS_EXPLOSIVE = new AmmoModel("AMMO_REPEATER_EXPRESS_EXPLOSIVE");
const AMMO_REPEATER_HIGH_VELOCITY = new AmmoModel("AMMO_REPEATER_HIGH_VELOCITY");
const AMMO_REPEATER_SPLIT_POINT = new AmmoModel("AMMO_REPEATER_SPLIT_POINT");
const AMMO_REVOLVER = new AmmoModel("AMMO_REVOLVER");
const AMMO_REVOLVER_EXPRESS = new AmmoModel("AMMO_REVOLVER_EXPRESS");
const AMMO_REVOLVER_EXPRESS_EXPLOSIVE = new AmmoModel("AMMO_REVOLVER_EXPRESS_EXPLOSIVE");
const AMMO_REVOLVER_HIGH_VELOCITY = new AmmoModel("AMMO_REVOLVER_HIGH_VELOCITY");
const AMMO_REVOLVER_SPLIT_POINT = new AmmoModel("AMMO_REVOLVER_SPLIT_POINT");
const AMMO_RIFLE = new AmmoModel("AMMO_RIFLE");
const AMMO_RIFLE_ELEPHANT = new AmmoModel("AMMO_RIFLE_ELEPHANT");
const AMMO_RIFLE_EXPRESS = new AmmoModel("AMMO_RIFLE_EXPRESS");
const AMMO_RIFLE_EXPRESS_EXPLOSIVE = new AmmoModel("AMMO_RIFLE_EXPRESS_EXPLOSIVE");
const AMMO_RIFLE_HIGH_VELOCITY = new AmmoModel("AMMO_RIFLE_HIGH_VELOCITY");
const AMMO_RIFLE_SPLIT_POINT = new AmmoModel("AMMO_RIFLE_SPLIT_POINT");
const AMMO_SHOTGUN = new AmmoModel("AMMO_SHOTGUN");
const AMMO_SHOTGUN_BUCKSHOT_INCENDIARY = new AmmoModel("AMMO_SHOTGUN_BUCKSHOT_INCENDIARY");
const AMMO_SHOTGUN_SLUG = new AmmoModel("AMMO_SHOTGUN_SLUG");
const AMMO_SHOTGUN_SLUG_EXPLOSIVE = new AmmoModel("AMMO_SHOTGUN_SLUG_EXPLOSIVE");
const AMMO_THROWING_KNIVES = new AmmoModel("AMMO_THROWING_KNIVES");
const AMMO_THROWING_KNIVES_CONFUSE = new AmmoModel("AMMO_THROWING_KNIVES_CONFUSE");
const AMMO_THROWING_KNIVES_DISORIENT = new AmmoModel("AMMO_THROWING_KNIVES_DISORIENT");
const AMMO_THROWING_KNIVES_DRAIN = new AmmoModel("AMMO_THROWING_KNIVES_DRAIN");
const AMMO_THROWING_KNIVES_IMPROVED = new AmmoModel("AMMO_THROWING_KNIVES_IMPROVED");
const AMMO_THROWING_KNIVES_JAVIER = new AmmoModel("AMMO_THROWING_KNIVES_JAVIER");
const AMMO_THROWING_KNIVES_POISON = new AmmoModel("AMMO_THROWING_KNIVES_POISON");
const AMMO_THROWING_KNIVES_TRAIL = new AmmoModel("AMMO_THROWING_KNIVES_TRAIL");
const AMMO_THROWING_KNIVES_WOUND = new AmmoModel("AMMO_THROWING_KNIVES_WOUND");
const AMMO_THROWN_ITEM = new AmmoModel("AMMO_THROWN_ITEM");
const AMMO_TOMAHAWK = new AmmoModel("AMMO_TOMAHAWK");
const AMMO_TOMAHAWK_ANCIENT = new AmmoModel("AMMO_TOMAHAWK_ANCIENT");
const AMMO_TOMAHAWK_HOMING = new AmmoModel("AMMO_TOMAHAWK_HOMING");
const AMMO_TOMAHAWK_IMPROVED = new AmmoModel("AMMO_TOMAHAWK_IMPROVED");
const AMMO_TURRET = new AmmoModel("AMMO_TURRET");
const AMMO_MAP = /* @__PURE__ */ new Map([
  ["ammo_22", AMMO_22],
  ["ammo_22_tranquilizer", AMMO_22_TRANQUILIZER],
  ["ammo_arrow", AMMO_ARROW],
  ["ammo_arrow_confusion", AMMO_ARROW_CONFUSION],
  ["ammo_arrow_disorient", AMMO_ARROW_DISORIENT],
  ["ammo_arrow_drain", AMMO_ARROW_DRAIN],
  ["ammo_arrow_dynamite", AMMO_ARROW_DYNAMITE],
  ["ammo_arrow_fire", AMMO_ARROW_FIRE],
  ["ammo_arrow_improved", AMMO_ARROW_IMPROVED],
  ["ammo_arrow_poison", AMMO_ARROW_POISON],
  ["ammo_arrow_small_game", AMMO_ARROW_SMALL_GAME],
  ["ammo_arrow_tracking", AMMO_ARROW_TRACKING],
  ["ammo_arrow_trail", AMMO_ARROW_TRAIL],
  ["ammo_arrow_wound", AMMO_ARROW_WOUND],
  ["ammo_bolas", AMMO_BOLAS],
  ["ammo_bolas_hawkmoth", AMMO_BOLAS_HAWKMOTH],
  ["ammo_bolas_intertwined", AMMO_BOLAS_INTERTWINED],
  ["ammo_bolas_ironspiked", AMMO_BOLAS_IRONSPIKED],
  ["ammo_cannon", AMMO_CANNON],
  ["ammo_dynamite", AMMO_DYNAMITE],
  ["ammo_dynamite_volatile", AMMO_DYNAMITE_VOLATILE],
  ["ammo_hatchet", AMMO_HATCHET],
  ["ammo_hatchet_ancient", AMMO_HATCHET_ANCIENT],
  ["ammo_hatchet_cleaver", AMMO_HATCHET_CLEAVER],
  ["ammo_hatchet_double_bit", AMMO_HATCHET_DOUBLE_BIT],
  ["ammo_hatchet_double_bit_rusted", AMMO_HATCHET_DOUBLE_BIT_RUSTED],
  ["ammo_hatchet_hewing", AMMO_HATCHET_HEWING],
  ["ammo_hatchet_hunter", AMMO_HATCHET_HUNTER],
  ["ammo_hatchet_hunter_rusted", AMMO_HATCHET_HUNTER_RUSTED],
  ["ammo_hatchet_viking", AMMO_HATCHET_VIKING],
  ["ammo_lasso", AMMO_LASSO],
  ["ammo_lasso_reinforced", AMMO_LASSO_REINFORCED],
  ["ammo_molotov", AMMO_MOLOTOV],
  ["ammo_molotov_volatile", AMMO_MOLOTOV_VOLATILE],
  ["ammo_moonshinejug", AMMO_MOONSHINEJUG],
  ["ammo_moonshinejug_mp", AMMO_MOONSHINEJUG_MP],
  ["ammo_pistol", AMMO_PISTOL],
  ["ammo_pistol_express", AMMO_PISTOL_EXPRESS],
  ["ammo_pistol_express_explosive", AMMO_PISTOL_EXPRESS_EXPLOSIVE],
  ["ammo_pistol_high_velocity", AMMO_PISTOL_HIGH_VELOCITY],
  ["ammo_pistol_split_point", AMMO_PISTOL_SPLIT_POINT],
  ["ammo_poisonbottle", AMMO_POISONBOTTLE],
  ["ammo_repeater", AMMO_REPEATER],
  ["ammo_repeater_express", AMMO_REPEATER_EXPRESS],
  ["ammo_repeater_express_explosive", AMMO_REPEATER_EXPRESS_EXPLOSIVE],
  ["ammo_repeater_high_velocity", AMMO_REPEATER_HIGH_VELOCITY],
  ["ammo_repeater_split_point", AMMO_REPEATER_SPLIT_POINT],
  ["ammo_revolver", AMMO_REVOLVER],
  ["ammo_revolver_express", AMMO_REVOLVER_EXPRESS],
  ["ammo_revolver_express_explosive", AMMO_REVOLVER_EXPRESS_EXPLOSIVE],
  ["ammo_revolver_high_velocity", AMMO_REVOLVER_HIGH_VELOCITY],
  ["ammo_revolver_split_point", AMMO_REVOLVER_SPLIT_POINT],
  ["ammo_rifle", AMMO_RIFLE],
  ["ammo_rifle_elephant", AMMO_RIFLE_ELEPHANT],
  ["ammo_rifle_express", AMMO_RIFLE_EXPRESS],
  ["ammo_rifle_express_explosive", AMMO_RIFLE_EXPRESS_EXPLOSIVE],
  ["ammo_rifle_high_velocity", AMMO_RIFLE_HIGH_VELOCITY],
  ["ammo_rifle_split_point", AMMO_RIFLE_SPLIT_POINT],
  ["ammo_shotgun", AMMO_SHOTGUN],
  ["ammo_shotgun_buckshot_incendiary", AMMO_SHOTGUN_BUCKSHOT_INCENDIARY],
  ["ammo_shotgun_slug", AMMO_SHOTGUN_SLUG],
  ["ammo_shotgun_slug_explosive", AMMO_SHOTGUN_SLUG_EXPLOSIVE],
  ["ammo_throwing_knives", AMMO_THROWING_KNIVES],
  ["ammo_throwing_knives_confuse", AMMO_THROWING_KNIVES_CONFUSE],
  ["ammo_throwing_knives_disorient", AMMO_THROWING_KNIVES_DISORIENT],
  ["ammo_throwing_knives_drain", AMMO_THROWING_KNIVES_DRAIN],
  ["ammo_throwing_knives_improved", AMMO_THROWING_KNIVES_IMPROVED],
  ["ammo_throwing_knives_javier", AMMO_THROWING_KNIVES_JAVIER],
  ["ammo_throwing_knives_poison", AMMO_THROWING_KNIVES_POISON],
  ["ammo_throwing_knives_trail", AMMO_THROWING_KNIVES_TRAIL],
  ["ammo_throwing_knives_wound", AMMO_THROWING_KNIVES_WOUND],
  ["ammo_thrown_item", AMMO_THROWN_ITEM],
  ["ammo_tomahawk", AMMO_TOMAHAWK],
  ["ammo_tomahawk_ancient", AMMO_TOMAHAWK_ANCIENT],
  ["ammo_tomahawk_homing", AMMO_TOMAHAWK_HOMING],
  ["ammo_tomahawk_improved", AMMO_TOMAHAWK_IMPROVED],
  ["ammo_turret", AMMO_TURRET]
]);
export {
  AMMO_22,
  AMMO_22_TRANQUILIZER,
  AMMO_ARROW,
  AMMO_ARROW_CONFUSION,
  AMMO_ARROW_DISORIENT,
  AMMO_ARROW_DRAIN,
  AMMO_ARROW_DYNAMITE,
  AMMO_ARROW_FIRE,
  AMMO_ARROW_IMPROVED,
  AMMO_ARROW_POISON,
  AMMO_ARROW_SMALL_GAME,
  AMMO_ARROW_TRACKING,
  AMMO_ARROW_TRAIL,
  AMMO_ARROW_WOUND,
  AMMO_BOLAS,
  AMMO_BOLAS_HAWKMOTH,
  AMMO_BOLAS_INTERTWINED,
  AMMO_BOLAS_IRONSPIKED,
  AMMO_CANNON,
  AMMO_DYNAMITE,
  AMMO_DYNAMITE_VOLATILE,
  AMMO_HATCHET,
  AMMO_HATCHET_ANCIENT,
  AMMO_HATCHET_CLEAVER,
  AMMO_HATCHET_DOUBLE_BIT,
  AMMO_HATCHET_DOUBLE_BIT_RUSTED,
  AMMO_HATCHET_HEWING,
  AMMO_HATCHET_HUNTER,
  AMMO_HATCHET_HUNTER_RUSTED,
  AMMO_HATCHET_VIKING,
  AMMO_LASSO,
  AMMO_LASSO_REINFORCED,
  AMMO_MAP,
  AMMO_MOLOTOV,
  AMMO_MOLOTOV_VOLATILE,
  AMMO_MOONSHINEJUG,
  AMMO_MOONSHINEJUG_MP,
  AMMO_PISTOL,
  AMMO_PISTOL_EXPRESS,
  AMMO_PISTOL_EXPRESS_EXPLOSIVE,
  AMMO_PISTOL_HIGH_VELOCITY,
  AMMO_PISTOL_SPLIT_POINT,
  AMMO_POISONBOTTLE,
  AMMO_REPEATER,
  AMMO_REPEATER_EXPRESS,
  AMMO_REPEATER_EXPRESS_EXPLOSIVE,
  AMMO_REPEATER_HIGH_VELOCITY,
  AMMO_REPEATER_SPLIT_POINT,
  AMMO_REVOLVER,
  AMMO_REVOLVER_EXPRESS,
  AMMO_REVOLVER_EXPRESS_EXPLOSIVE,
  AMMO_REVOLVER_HIGH_VELOCITY,
  AMMO_REVOLVER_SPLIT_POINT,
  AMMO_RIFLE,
  AMMO_RIFLE_ELEPHANT,
  AMMO_RIFLE_EXPRESS,
  AMMO_RIFLE_EXPRESS_EXPLOSIVE,
  AMMO_RIFLE_HIGH_VELOCITY,
  AMMO_RIFLE_SPLIT_POINT,
  AMMO_SHOTGUN,
  AMMO_SHOTGUN_BUCKSHOT_INCENDIARY,
  AMMO_SHOTGUN_SLUG,
  AMMO_SHOTGUN_SLUG_EXPLOSIVE,
  AMMO_THROWING_KNIVES,
  AMMO_THROWING_KNIVES_CONFUSE,
  AMMO_THROWING_KNIVES_DISORIENT,
  AMMO_THROWING_KNIVES_DRAIN,
  AMMO_THROWING_KNIVES_IMPROVED,
  AMMO_THROWING_KNIVES_JAVIER,
  AMMO_THROWING_KNIVES_POISON,
  AMMO_THROWING_KNIVES_TRAIL,
  AMMO_THROWING_KNIVES_WOUND,
  AMMO_THROWN_ITEM,
  AMMO_TOMAHAWK,
  AMMO_TOMAHAWK_ANCIENT,
  AMMO_TOMAHAWK_HOMING,
  AMMO_TOMAHAWK_IMPROVED,
  AMMO_TURRET
};
