import { Vector3 } from "./common/utils/Vector";
import { BaseEntity } from "./entities/BaseEntity";
import { Ped } from "./entities/Ped";
import type { Vehicle } from "./entities/Vehicle";
import type { AnimationFlags, IkControlFlags } from "./enums/AnimationFlags";
import { DrivingStyle } from "./enums/Driving";
import { FiringPatterns } from "./enums/FiringPatterns";
import { VehicleSeat } from "./enums/VehicleSeat";
export declare class Tasks {
    private ped;
    constructor(ped: Ped | null);
    achieveHeading(heading: number, timeout?: number): void;
    blockTemporaryEvents(block?: boolean): void;
    aimAt(target: BaseEntity | Vector3, duration: number): void;
    arrest(ped: Ped): void;
    jump(): void;
    climb(): void;
    cruiseWithVehicle(vehicle: Vehicle, speed: number, drivingStyle?: DrivingStyle): void;
    enterAnyVehicle(seat?: VehicleSeat, timeout?: number, speed?: number, flag?: number): void;
    static everyoneLeaveVehicle(vehicle: Vehicle): void;
    fightAgainst(target: Ped, duration?: number): void;
    fightAgainstHatedTargets(radius: number, duration?: number): void;
    fleeFrom(pedOrPosition: Ped | Vector3, distance?: number, duration?: number, fleeType?: number, fleeSpeed?: number, fleeFrom?: Ped): void;
    goTo(position: Vector3, ignorePaths?: boolean, timeout?: number, speed?: number, targetHeading?: number, distanceToSlide?: number, flags?: number): void;
    goToEntity(target: BaseEntity, offset?: Vector3 | null, timeout?: number): void;
    guardCurrentPosition(): void;
    handsUp(duration: number): void;
    lookAt(targetOrPosition: BaseEntity | Vector3, duration?: number): void;
    playAnimation(animDict: string, animName: string, blendInSpeed: number, blendOutSpeed: number, duration: number, playbackRate: number, animFlags: AnimationFlags, ikFlags: IkControlFlags): Promise<void>;
    reloadWeapon(): void;
    shootAt(targetOrPosition: Ped | Vector3, duration?: number, pattern?: FiringPatterns, affectCockedState?: boolean): void;
    shuffleToNextVehicleSeat(vehicle: Vehicle): void;
    slideTo(position: Vector3, heading: number, duration?: number): void;
    standStill(duration: number): void;
    vehicleShootAtPed(target: Ped): void;
    wait(duration: number): void;
    wanderAround(position?: Vector3, radius?: number): void;
    warpIntoVehicle(vehicle: Vehicle, seat: VehicleSeat): void;
    warpOutOfVehicle(vehicle: Vehicle, flags: EnterExitVehicleFlags): void;
    isPlayingAnim(dict: string, anim: string, taskFlag?: number): boolean;
    clearAll(): void;
    clearAllImmediately(): void;
    clearLookAt(): void;
    clearSecondary(): void;
    clearAnimation(animDict: string, animName: string): void;
}
