import { WeaponModel } from "./models/WeaponModel";
const WEAPON_UNARMED = new WeaponModel("WEAPON_UNARMED");
const WEAPON_MELEE_HATCHET_MELEEONLY = new WeaponModel("WEAPON_MELEE_HATCHET_MELEEONLY");
const WEAPON_MELEE_KNIFE_MINER = new WeaponModel("WEAPON_MELEE_KNIFE_MINER");
const WEAPON_MELEE_KNIFE_JAWBONE = new WeaponModel("WEAPON_MELEE_KNIFE_JAWBONE");
const WEAPON_MELEE_KNIFE_VAMPIRE = new WeaponModel("WEAPON_MELEE_KNIFE_VAMPIRE");
const WEAPON_MELEE_KNIFE_JOHN = new WeaponModel("WEAPON_MELEE_KNIFE_JOHN");
const WEAPON_MELEE_MACHETE = new WeaponModel("WEAPON_MELEE_MACHETE");
const WEAPON_MELEE_KNIFE_BEAR = new WeaponModel("WEAPON_MELEE_KNIFE_BEAR");
const WEAPON_MELEE_KNIFE_DUTCH = new WeaponModel("WEAPON_MELEE_KNIFE_DUTCH");
const WEAPON_MELEE_KNIFE_KIERAN = new WeaponModel("WEAPON_MELEE_KNIFE_KIERAN");
const WEAPON_MELEE_KNIFE_UNCLE = new WeaponModel("WEAPON_MELEE_KNIFE_UNCLE");
const WEAPON_MELEE_KNIFE_SEAN = new WeaponModel("WEAPON_MELEE_KNIFE_SEAN");
const WEAPON_MELEE_TORCH = new WeaponModel("WEAPON_MELEE_TORCH");
const WEAPON_MELEE_KNIFE_LENNY = new WeaponModel("WEAPON_MELEE_KNIFE_LENNY");
const WEAPON_MELEE_KNIFE_SADIE = new WeaponModel("WEAPON_MELEE_KNIFE_SADIE");
const WEAPON_MELEE_KNIFE_CHARLES = new WeaponModel("WEAPON_MELEE_KNIFE_CHARLES");
const WEAPON_MELEE_KNIFE_HOSEA = new WeaponModel("WEAPON_MELEE_KNIFE_HOSEA");
const WEAPON_MELEE_TORCH_CROWD = new WeaponModel("WEAPON_MELEE_TORCH_CROWD");
const WEAPON_MELEE_KNIFE_BILL = new WeaponModel("WEAPON_MELEE_KNIFE_BILL");
const WEAPON_MELEE_KNIFE_CIVIL_WAR = new WeaponModel("WEAPON_MELEE_KNIFE_CIVIL_WAR");
const WEAPON_MELEE_KNIFE = new WeaponModel("WEAPON_MELEE_KNIFE");
const WEAPON_MELEE_KNIFE_MICAH = new WeaponModel("WEAPON_MELEE_KNIFE_MICAH");
const WEAPON_MELEE_BROKEN_SWORD = new WeaponModel("WEAPON_MELEE_BROKEN_SWORD");
const WEAPON_MELEE_KNIFE_JAVIER = new WeaponModel("WEAPON_MELEE_KNIFE_JAVIER");
const WEAPON_PISTOL_VOLCANIC = new WeaponModel("WEAPON_PISTOL_VOLCANIC");
const WEAPON_PISTOL_MAUSER_DRUNK = new WeaponModel("WEAPON_PISTOL_MAUSER_DRUNK");
const WEAPON_PISTOL_M1899 = new WeaponModel("WEAPON_PISTOL_M1899");
const WEAPON_PISTOL_SEMIAUTO = new WeaponModel("WEAPON_PISTOL_SEMIAUTO");
const WEAPON_PISTOL_MAUSER = new WeaponModel("WEAPON_PISTOL_MAUSER");
const WEAPON_REPEATER_EVANS = new WeaponModel("WEAPON_REPEATER_EVANS");
const WEAPON_REPEATER_CARBINE_SADIE = new WeaponModel("WEAPON_REPEATER_CARBINE_SADIE");
const WEAPON_REPEATER_HENRY = new WeaponModel("WEAPON_REPEATER_HENRY");
const WEAPON_REPEATER_WINCHESTER = new WeaponModel("WEAPON_REPEATER_WINCHESTER");
const WEAPON_REPEATER_WINCHESTER_JOHN = new WeaponModel("WEAPON_REPEATER_WINCHESTER_JOHN");
const WEAPON_REPEATER_CARBINE = new WeaponModel("WEAPON_REPEATER_CARBINE");
const WEAPON_REVOLVER_DOUBLEACTION_MICAH_DUALWIELD = new WeaponModel(
  "WEAPON_REVOLVER_DOUBLEACTION_MICAH_DUALWIELD"
);
const WEAPON_REVOLVER_DOUBLEACTION_MICAH = new WeaponModel("WEAPON_REVOLVER_DOUBLEACTION_MICAH");
const WEAPON_REVOLVER_SCHOFIELD_CALLOWAY = new WeaponModel("WEAPON_REVOLVER_SCHOFIELD_CALLOWAY");
const WEAPON_REVOLVER_DOUBLEACTION = new WeaponModel("WEAPON_REVOLVER_DOUBLEACTION");
const WEAPON_REVOLVER_CATTLEMAN = new WeaponModel("WEAPON_REVOLVER_CATTLEMAN");
const WEAPON_REVOLVER_CATTLEMAN_MEXICAN = new WeaponModel("WEAPON_REVOLVER_CATTLEMAN_MEXICAN");
const WEAPON_REVOLVER_CATTLEMAN_HOSEA_DUALWIELD = new WeaponModel("WEAPON_REVOLVER_CATTLEMAN_HOSEA_DUALWIELD");
const WEAPON_REVOLVER_DOUBLEACTION_EXOTIC = new WeaponModel("WEAPON_REVOLVER_DOUBLEACTION_EXOTIC");
const WEAPON_REVOLVER_CATTLEMAN_SEAN = new WeaponModel("WEAPON_REVOLVER_CATTLEMAN_SEAN");
const WEAPON_REVOLVER_CATTLEMAN_SADIE = new WeaponModel("WEAPON_REVOLVER_CATTLEMAN_SADIE");
const WEAPON_REVOLVER_DOUBLEACTION_JAVIER = new WeaponModel("WEAPON_REVOLVER_DOUBLEACTION_JAVIER");
const WEAPON_REVOLVER_LEMAT = new WeaponModel("WEAPON_REVOLVER_LEMAT");
const WEAPON_REVOLVER_SCHOFIELD_BILL = new WeaponModel("WEAPON_REVOLVER_SCHOFIELD_BILL");
const WEAPON_REVOLVER_SCHOFIELD = new WeaponModel("WEAPON_REVOLVER_SCHOFIELD");
const WEAPON_REVOLVER_CATTLEMAN_SADIE_DUALWIELD = new WeaponModel("WEAPON_REVOLVER_CATTLEMAN_SADIE_DUALWIELD");
const WEAPON_REVOLVER_DOUBLEACTION_GAMBLER = new WeaponModel("WEAPON_REVOLVER_DOUBLEACTION_GAMBLER");
const WEAPON_REVOLVER_CATTLEMAN_KIERAN = new WeaponModel("WEAPON_REVOLVER_CATTLEMAN_KIERAN");
const WEAPON_REVOLVER_SCHOFIELD_UNCLE = new WeaponModel("WEAPON_REVOLVER_SCHOFIELD_UNCLE");
const WEAPON_REVOLVER_CATTLEMAN_HOSEA = new WeaponModel("WEAPON_REVOLVER_CATTLEMAN_HOSEA");
const WEAPON_REVOLVER_CATTLEMAN_LENNY = new WeaponModel("WEAPON_REVOLVER_CATTLEMAN_LENNY");
const WEAPON_REVOLVER_CATTLEMAN_JOHN = new WeaponModel("WEAPON_REVOLVER_CATTLEMAN_JOHN");
const WEAPON_REVOLVER_SCHOFIELD_DUTCH_DUALWIELD = new WeaponModel("WEAPON_REVOLVER_SCHOFIELD_DUTCH_DUALWIELD");
const WEAPON_REVOLVER_SCHOFIELD_GOLDEN = new WeaponModel("WEAPON_REVOLVER_SCHOFIELD_GOLDEN");
const WEAPON_REVOLVER_CATTLEMAN_PIG = new WeaponModel("WEAPON_REVOLVER_CATTLEMAN_PIG");
const WEAPON_REVOLVER_SCHOFIELD_DUTCH = new WeaponModel("WEAPON_REVOLVER_SCHOFIELD_DUTCH");
const WEAPON_RIFLE_SPRINGFIELD = new WeaponModel("WEAPON_RIFLE_SPRINGFIELD");
const WEAPON_RIFLE_BOLTACTION = new WeaponModel("WEAPON_RIFLE_BOLTACTION");
const WEAPON_RIFLE_BOLTACTION_BILL = new WeaponModel("WEAPON_RIFLE_BOLTACTION_BILL");
const WEAPON_RIFLE_VARMINT = new WeaponModel("WEAPON_RIFLE_VARMINT");
const WEAPON_SHOTGUN_SAWEDOFF = new WeaponModel("WEAPON_SHOTGUN_SAWEDOFF");
const WEAPON_SHOTGUN_DOUBLEBARREL_EXOTIC = new WeaponModel("WEAPON_SHOTGUN_DOUBLEBARREL_EXOTIC");
const WEAPON_SHOTGUN_PUMP = new WeaponModel("WEAPON_SHOTGUN_PUMP");
const WEAPON_SHOTGUN_REPEATING = new WeaponModel("WEAPON_SHOTGUN_REPEATING");
const WEAPON_SHOTGUN_SEMIAUTO = new WeaponModel("WEAPON_SHOTGUN_SEMIAUTO");
const WEAPON_SHOTGUN_DOUBLEBARREL = new WeaponModel("WEAPON_SHOTGUN_DOUBLEBARREL");
const WEAPON_SHOTGUN_DOUBLEBARREL_UNCLE = new WeaponModel("WEAPON_SHOTGUN_DOUBLEBARREL_UNCLE");
const WEAPON_SHOTGUN_SAWEDOFF_CHARLES = new WeaponModel("WEAPON_SHOTGUN_SAWEDOFF_CHARLES");
const WEAPON_SHOTGUN_SEMIAUTO_HOSEA = new WeaponModel("WEAPON_SHOTGUN_SEMIAUTO_HOSEA");
const WEAPON_SNIPERRIFLE_ROLLINGBLOCK_LENNY = new WeaponModel("WEAPON_SNIPERRIFLE_ROLLINGBLOCK_LENNY");
const WEAPON_SNIPERRIFLE_ROLLINGBLOCK_EXOTIC = new WeaponModel("WEAPON_SNIPERRIFLE_ROLLINGBLOCK_EXOTIC");
const WEAPON_SNIPERRIFLE_CARCANO = new WeaponModel("WEAPON_SNIPERRIFLE_CARCANO");
const WEAPON_SNIPERRIFLE_ROLLINGBLOCK = new WeaponModel("WEAPON_SNIPERRIFLE_ROLLINGBLOCK");
const WEAPON_MELEE_HATCHET = new WeaponModel("WEAPON_MELEE_HATCHET");
const WEAPON_MELEE_HATCHET_HEWING = new WeaponModel("WEAPON_MELEE_HATCHET_HEWING");
const WEAPON_MELEE_ANCIENT_HATCHET = new WeaponModel("WEAPON_MELEE_ANCIENT_HATCHET");
const WEAPON_MELEE_HATCHET_HUNTER = new WeaponModel("WEAPON_MELEE_HATCHET_HUNTER");
const WEAPON_THROWN_THROWING_KNIVES_JAVIER = new WeaponModel("WEAPON_THROWN_THROWING_KNIVES_JAVIER");
const WEAPON_THROWN_MOLOTOV = new WeaponModel("WEAPON_THROWN_MOLOTOV");
const WEAPON_MELEE_HATCHET_VIKING = new WeaponModel("WEAPON_MELEE_HATCHET_VIKING");
const WEAPON_THROWN_TOMAHAWK_ANCIENT = new WeaponModel("WEAPON_THROWN_TOMAHAWK_ANCIENT");
const WEAPON_MELEE_HATCHET_DOUBLE_BIT_RUSTED = new WeaponModel("WEAPON_MELEE_HATCHET_DOUBLE_BIT_RUSTED");
const WEAPON_THROWN_TOMAHAWK = new WeaponModel("WEAPON_THROWN_TOMAHAWK");
const WEAPON_THROWN_DYNAMITE = new WeaponModel("WEAPON_THROWN_DYNAMITE");
const WEAPON_MELEE_HATCHET_DOUBLE_BIT = new WeaponModel("WEAPON_MELEE_HATCHET_DOUBLE_BIT");
const WEAPON_THROWN_THROWING_KNIVES = new WeaponModel("WEAPON_THROWN_THROWING_KNIVES");
const WEAPON_MELEE_HATCHET_HUNTER_RUSTED = new WeaponModel("WEAPON_MELEE_HATCHET_HUNTER_RUSTED");
const WEAPON_MELEE_CLEAVER = new WeaponModel("WEAPON_MELEE_CLEAVER");
const WEAPON_MELEE_LANTERN = new WeaponModel("WEAPON_MELEE_LANTERN");
const WEAPON_MELEE_DAVY_LANTERN = new WeaponModel("WEAPON_MELEE_DAVY_LANTERN");
const WEAPON_MELEE_LANTERN_ELECTRIC = new WeaponModel("WEAPON_MELEE_LANTERN_ELECTRIC");
const WEAPON_KIT_BINOCULARS = new WeaponModel("WEAPON_KIT_BINOCULARS");
const WEAPON_KIT_CAMERA = new WeaponModel("WEAPON_KIT_CAMERA");
const WEAPON_KIT_DETECTOR = new WeaponModel("WEAPON_KIT_DETECTOR");
const WEAPON_BOW_CHARLES = new WeaponModel("WEAPON_BOW_CHARLES");
const WEAPON_BOW = new WeaponModel("WEAPON_BOW");
const WEAPON_FISHINGROD = new WeaponModel("WEAPON_FISHINGROD");
const WEAPON_LASSO = new WeaponModel("WEAPON_LASSO");
const WEAPON_WOLF = new WeaponModel("WEAPON_WOLF");
const WEAPON_WOLF_MEDIUM = new WeaponModel("WEAPON_WOLF_MEDIUM");
const WEAPON_WOLF_SMALL = new WeaponModel("WEAPON_WOLF_SMALL");
const WEAPON_ALLIGATOR = new WeaponModel("WEAPON_ALLIGATOR");
const WEAPON_ANIMAL = new WeaponModel("WEAPON_ANIMAL");
const WEAPON_BADGER = new WeaponModel("WEAPON_BADGER");
const WEAPON_BEAR = new WeaponModel("WEAPON_BEAR");
const WEAPON_BEAVER = new WeaponModel("WEAPON_BEAVER");
const WEAPON_COUGAR = new WeaponModel("WEAPON_COUGAR");
const WEAPON_COYOTE = new WeaponModel("WEAPON_COYOTE");
const WEAPON_DEER = new WeaponModel("WEAPON_DEER");
const WEAPON_FOX = new WeaponModel("WEAPON_FOX");
const WEAPON_HORSE = new WeaponModel("WEAPON_HORSE");
const WEAPON_MUSKRAT = new WeaponModel("WEAPON_MUSKRAT");
const WEAPON_RACCOON = new WeaponModel("WEAPON_RACCOON");
const WEAPON_SNAKE = new WeaponModel("WEAPON_SNAKE");
const WEAPON_FALL = new WeaponModel("WEAPON_FALL");
const WEAPON_FIRE = new WeaponModel("WEAPON_FIRE");
const WEAPON_BLEEDING = new WeaponModel("WEAPON_BLEEDING");
const WEAPON_DROWNING = new WeaponModel("WEAPON_DROWNING");
const WEAPON_DROWNING_IN_VEHICLE = new WeaponModel("WEAPON_DROWNING_IN_VEHICLE");
const WEAPON_EXPLOSION = new WeaponModel("WEAPON_EXPLOSION");
const WEAPON_RAMMED_BY_CAR = new WeaponModel("WEAPON_RAMMED_BY_CAR");
const WEAPON_RUN_OVER_BY_CAR = new WeaponModel("WEAPON_RUN_OVER_BY_CAR");
const WEAPON_KIT_CAMERA_ADVANCED = new WeaponModel("WEAPON_KIT_CAMERA_ADVANCED");
const WEAPON_MELEE_MACHETE_HORROR = new WeaponModel("WEAPON_MELEE_MACHETE_HORROR");
const WEAPON_BOW_IMPROVED = new WeaponModel("WEAPON_BOW_IMPROVED");
const WEAPON_RIFLE_ELEPHANT = new WeaponModel("WEAPON_RIFLE_ELEPHANT");
const WEAPON_REVOLVER_NAVY = new WeaponModel("WEAPON_REVOLVER_NAVY");
const WEAPON_LASSO_REINFORCED = new WeaponModel("WEAPON_LASSO_REINFORCED");
const WEAPON_KIT_BINOCULARS_IMPROVED = new WeaponModel("WEAPON_KIT_BINOCULARS_IMPROVED");
const WEAPON_MELEE_KNIFE_TRADER = new WeaponModel("WEAPON_MELEE_KNIFE_TRADER");
const WEAPON_MELEE_MACHETE_COLLECTOR = new WeaponModel("WEAPON_MELEE_MACHETE_COLLECTOR");
const WEAPON_MOONSHINEJUG_MP = new WeaponModel("WEAPON_MOONSHINEJUG_MP");
const WEAPON_THROWN_BOLAS = new WeaponModel("WEAPON_THROWN_BOLAS");
const WEAPON_THROWN_POISONBOTTLE = new WeaponModel("WEAPON_THROWN_POISONBOTTLE");
const WEAPON_KIT_METAL_DETECTOR = new WeaponModel("WEAPON_KIT_METAL_DETECTOR");
const WEAPON_REVOLVER_NAVY_CROSSOVER = new WeaponModel("WEAPON_REVOLVER_NAVY_CROSSOVER");
const WEAPON_THROWN_BOLAS_HAWKMOTH = new WeaponModel("WEAPON_THROWN_BOLAS_HAWKMOTH");
const WEAPON_THROWN_BOLAS_IRONSPIKED = new WeaponModel("WEAPON_THROWN_BOLAS_IRONSPIKED");
const WEAPON_THROWN_BOLAS_INTERTWINED = new WeaponModel("WEAPON_THROWN_BOLAS_INTERTWINED");
const WEAPON_MELEE_KNIFE_HORROR = new WeaponModel("WEAPON_MELEE_KNIFE_HORROR");
const WEAPON_MELEE_KNIFE_RUSTIC = new WeaponModel("WEAPON_MELEE_KNIFE_RUSTIC");
const WEAPON_MELEE_LANTERN_HALLOWEEN = new WeaponModel("WEAPON_MELEE_LANTERN_HALLOWEEN");
const WEAPONS_MAP = /* @__PURE__ */ new Map([
  ["weapon_unarmed", WEAPON_UNARMED],
  ["weapon_melee_hatchet_meleeonly", WEAPON_MELEE_HATCHET_MELEEONLY],
  ["weapon_melee_knife_miner", WEAPON_MELEE_KNIFE_MINER],
  ["weapon_melee_knife_jawbone", WEAPON_MELEE_KNIFE_JAWBONE],
  ["weapon_melee_knife_vampire", WEAPON_MELEE_KNIFE_VAMPIRE],
  ["weapon_melee_knife_john", WEAPON_MELEE_KNIFE_JOHN],
  ["weapon_melee_machete", WEAPON_MELEE_MACHETE],
  ["weapon_melee_knife_bear", WEAPON_MELEE_KNIFE_BEAR],
  ["weapon_melee_knife_dutch", WEAPON_MELEE_KNIFE_DUTCH],
  ["weapon_melee_knife_kieran", WEAPON_MELEE_KNIFE_KIERAN],
  ["weapon_melee_knife_uncle", WEAPON_MELEE_KNIFE_UNCLE],
  ["weapon_melee_knife_sean", WEAPON_MELEE_KNIFE_SEAN],
  ["weapon_melee_torch", WEAPON_MELEE_TORCH],
  ["weapon_melee_knife_lenny", WEAPON_MELEE_KNIFE_LENNY],
  ["weapon_melee_knife_sadie", WEAPON_MELEE_KNIFE_SADIE],
  ["weapon_melee_knife_charles", WEAPON_MELEE_KNIFE_CHARLES],
  ["weapon_melee_knife_hosea", WEAPON_MELEE_KNIFE_HOSEA],
  ["weapon_melee_torch_crowd", WEAPON_MELEE_TORCH_CROWD],
  ["weapon_melee_knife_bill", WEAPON_MELEE_KNIFE_BILL],
  ["weapon_melee_knife_civil_war", WEAPON_MELEE_KNIFE_CIVIL_WAR],
  ["weapon_melee_knife", WEAPON_MELEE_KNIFE],
  ["weapon_melee_knife_micah", WEAPON_MELEE_KNIFE_MICAH],
  ["weapon_melee_broken_sword", WEAPON_MELEE_BROKEN_SWORD],
  ["weapon_melee_knife_javier", WEAPON_MELEE_KNIFE_JAVIER],
  ["weapon_pistol_volcanic", WEAPON_PISTOL_VOLCANIC],
  ["weapon_pistol_mauser_drunk", WEAPON_PISTOL_MAUSER_DRUNK],
  ["weapon_pistol_m1899", WEAPON_PISTOL_M1899],
  ["weapon_pistol_semiauto", WEAPON_PISTOL_SEMIAUTO],
  ["weapon_pistol_mauser", WEAPON_PISTOL_MAUSER],
  ["weapon_repeater_evans", WEAPON_REPEATER_EVANS],
  ["weapon_repeater_carbine_sadie", WEAPON_REPEATER_CARBINE_SADIE],
  ["weapon_repeater_henry", WEAPON_REPEATER_HENRY],
  ["weapon_repeater_winchester", WEAPON_REPEATER_WINCHESTER],
  ["weapon_repeater_winchester_john", WEAPON_REPEATER_WINCHESTER_JOHN],
  ["weapon_repeater_carbine", WEAPON_REPEATER_CARBINE],
  ["weapon_revolver_doubleaction_micah_dualwield", WEAPON_REVOLVER_DOUBLEACTION_MICAH_DUALWIELD],
  ["weapon_revolver_doubleaction_micah", WEAPON_REVOLVER_DOUBLEACTION_MICAH],
  ["weapon_revolver_schofield_calloway", WEAPON_REVOLVER_SCHOFIELD_CALLOWAY],
  ["weapon_revolver_doubleaction", WEAPON_REVOLVER_DOUBLEACTION],
  ["weapon_revolver_cattleman", WEAPON_REVOLVER_CATTLEMAN],
  ["weapon_revolver_cattleman_mexican", WEAPON_REVOLVER_CATTLEMAN_MEXICAN],
  ["weapon_revolver_cattleman_hosea_dualwield", WEAPON_REVOLVER_CATTLEMAN_HOSEA_DUALWIELD],
  ["weapon_revolver_doubleaction_exotic", WEAPON_REVOLVER_DOUBLEACTION_EXOTIC],
  ["weapon_revolver_cattleman_sean", WEAPON_REVOLVER_CATTLEMAN_SEAN],
  ["weapon_revolver_cattleman_sadie", WEAPON_REVOLVER_CATTLEMAN_SADIE],
  ["weapon_revolver_doubleaction_javier", WEAPON_REVOLVER_DOUBLEACTION_JAVIER],
  ["weapon_revolver_lemat", WEAPON_REVOLVER_LEMAT],
  ["weapon_revolver_schofield_bill", WEAPON_REVOLVER_SCHOFIELD_BILL],
  ["weapon_revolver_schofield", WEAPON_REVOLVER_SCHOFIELD],
  ["weapon_revolver_cattleman_sadie_dualwield", WEAPON_REVOLVER_CATTLEMAN_SADIE_DUALWIELD],
  ["weapon_revolver_doubleaction_gambler", WEAPON_REVOLVER_DOUBLEACTION_GAMBLER],
  ["weapon_revolver_cattleman_kieran", WEAPON_REVOLVER_CATTLEMAN_KIERAN],
  ["weapon_revolver_schofield_uncle", WEAPON_REVOLVER_SCHOFIELD_UNCLE],
  ["weapon_revolver_cattleman_hosea", WEAPON_REVOLVER_CATTLEMAN_HOSEA],
  ["weapon_revolver_cattleman_lenny", WEAPON_REVOLVER_CATTLEMAN_LENNY],
  ["weapon_revolver_cattleman_john", WEAPON_REVOLVER_CATTLEMAN_JOHN],
  ["weapon_revolver_schofield_dutch_dualwield", WEAPON_REVOLVER_SCHOFIELD_DUTCH_DUALWIELD],
  ["weapon_revolver_schofield_golden", WEAPON_REVOLVER_SCHOFIELD_GOLDEN],
  ["weapon_revolver_cattleman_pig", WEAPON_REVOLVER_CATTLEMAN_PIG],
  ["weapon_revolver_schofield_dutch", WEAPON_REVOLVER_SCHOFIELD_DUTCH],
  ["weapon_rifle_springfield", WEAPON_RIFLE_SPRINGFIELD],
  ["weapon_rifle_boltaction", WEAPON_RIFLE_BOLTACTION],
  ["weapon_rifle_boltaction_bill", WEAPON_RIFLE_BOLTACTION_BILL],
  ["weapon_rifle_varmint", WEAPON_RIFLE_VARMINT],
  ["weapon_shotgun_sawedoff", WEAPON_SHOTGUN_SAWEDOFF],
  ["weapon_shotgun_doublebarrel_exotic", WEAPON_SHOTGUN_DOUBLEBARREL_EXOTIC],
  ["weapon_shotgun_pump", WEAPON_SHOTGUN_PUMP],
  ["weapon_shotgun_repeating", WEAPON_SHOTGUN_REPEATING],
  ["weapon_shotgun_semiauto", WEAPON_SHOTGUN_SEMIAUTO],
  ["weapon_shotgun_doublebarrel", WEAPON_SHOTGUN_DOUBLEBARREL],
  ["weapon_shotgun_doublebarrel_uncle", WEAPON_SHOTGUN_DOUBLEBARREL_UNCLE],
  ["weapon_shotgun_sawedoff_charles", WEAPON_SHOTGUN_SAWEDOFF_CHARLES],
  ["weapon_shotgun_semiauto_hosea", WEAPON_SHOTGUN_SEMIAUTO_HOSEA],
  ["weapon_sniperrifle_rollingblock_lenny", WEAPON_SNIPERRIFLE_ROLLINGBLOCK_LENNY],
  ["weapon_sniperrifle_rollingblock_exotic", WEAPON_SNIPERRIFLE_ROLLINGBLOCK_EXOTIC],
  ["weapon_sniperrifle_carcano", WEAPON_SNIPERRIFLE_CARCANO],
  ["weapon_sniperrifle_rollingblock", WEAPON_SNIPERRIFLE_ROLLINGBLOCK],
  ["weapon_melee_hatchet", WEAPON_MELEE_HATCHET],
  ["weapon_melee_hatchet_hewing", WEAPON_MELEE_HATCHET_HEWING],
  ["weapon_melee_ancient_hatchet", WEAPON_MELEE_ANCIENT_HATCHET],
  ["weapon_melee_hatchet_hunter", WEAPON_MELEE_HATCHET_HUNTER],
  ["weapon_thrown_throwing_knives_javier", WEAPON_THROWN_THROWING_KNIVES_JAVIER],
  ["weapon_thrown_molotov", WEAPON_THROWN_MOLOTOV],
  ["weapon_melee_hatchet_viking", WEAPON_MELEE_HATCHET_VIKING],
  ["weapon_thrown_tomahawk_ancient", WEAPON_THROWN_TOMAHAWK_ANCIENT],
  ["weapon_melee_hatchet_double_bit_rusted", WEAPON_MELEE_HATCHET_DOUBLE_BIT_RUSTED],
  ["weapon_thrown_tomahawk", WEAPON_THROWN_TOMAHAWK],
  ["weapon_thrown_dynamite", WEAPON_THROWN_DYNAMITE],
  ["weapon_melee_hatchet_double_bit", WEAPON_MELEE_HATCHET_DOUBLE_BIT],
  ["weapon_thrown_throwing_knives", WEAPON_THROWN_THROWING_KNIVES],
  ["weapon_melee_hatchet_hunter_rusted", WEAPON_MELEE_HATCHET_HUNTER_RUSTED],
  ["weapon_melee_cleaver", WEAPON_MELEE_CLEAVER],
  ["weapon_melee_lantern", WEAPON_MELEE_LANTERN],
  ["weapon_melee_davy_lantern", WEAPON_MELEE_DAVY_LANTERN],
  ["weapon_melee_lantern_electric", WEAPON_MELEE_LANTERN_ELECTRIC],
  ["weapon_kit_binoculars", WEAPON_KIT_BINOCULARS],
  ["weapon_kit_camera", WEAPON_KIT_CAMERA],
  ["weapon_kit_detector", WEAPON_KIT_DETECTOR],
  ["weapon_bow_charles", WEAPON_BOW_CHARLES],
  ["weapon_bow", WEAPON_BOW],
  ["weapon_fishingrod", WEAPON_FISHINGROD],
  ["weapon_lasso", WEAPON_LASSO],
  ["weapon_wolf", WEAPON_WOLF],
  ["weapon_wolf_medium", WEAPON_WOLF_MEDIUM],
  ["weapon_wolf_small", WEAPON_WOLF_SMALL],
  ["weapon_alligator", WEAPON_ALLIGATOR],
  ["weapon_animal", WEAPON_ANIMAL],
  ["weapon_badger", WEAPON_BADGER],
  ["weapon_bear", WEAPON_BEAR],
  ["weapon_beaver", WEAPON_BEAVER],
  ["weapon_cougar", WEAPON_COUGAR],
  ["weapon_coyote", WEAPON_COYOTE],
  ["weapon_deer", WEAPON_DEER],
  ["weapon_fox", WEAPON_FOX],
  ["weapon_horse", WEAPON_HORSE],
  ["weapon_muskrat", WEAPON_MUSKRAT],
  ["weapon_raccoon", WEAPON_RACCOON],
  ["weapon_snake", WEAPON_SNAKE],
  ["weapon_fall", WEAPON_FALL],
  ["weapon_fire", WEAPON_FIRE],
  ["weapon_bleeding", WEAPON_BLEEDING],
  ["weapon_drowning", WEAPON_DROWNING],
  ["weapon_drowning_in_vehicle", WEAPON_DROWNING_IN_VEHICLE],
  ["weapon_explosion", WEAPON_EXPLOSION],
  ["weapon_rammed_by_car", WEAPON_RAMMED_BY_CAR],
  ["weapon_run_over_by_car", WEAPON_RUN_OVER_BY_CAR],
  ["weapon_kit_camera_advanced", WEAPON_KIT_CAMERA_ADVANCED],
  ["weapon_melee_machete_horror", WEAPON_MELEE_MACHETE_HORROR],
  ["weapon_bow_improved", WEAPON_BOW_IMPROVED],
  ["weapon_rifle_elephant", WEAPON_RIFLE_ELEPHANT],
  ["weapon_revolver_navy", WEAPON_REVOLVER_NAVY],
  ["weapon_lasso_reinforced", WEAPON_LASSO_REINFORCED],
  ["weapon_kit_binoculars_improved", WEAPON_KIT_BINOCULARS_IMPROVED],
  ["weapon_melee_knife_trader", WEAPON_MELEE_KNIFE_TRADER],
  ["weapon_melee_machete_collector", WEAPON_MELEE_MACHETE_COLLECTOR],
  ["weapon_moonshinejug_mp", WEAPON_MOONSHINEJUG_MP],
  ["weapon_thrown_bolas", WEAPON_THROWN_BOLAS],
  ["weapon_thrown_poisonbottle", WEAPON_THROWN_POISONBOTTLE],
  ["weapon_kit_metal_detector", WEAPON_KIT_METAL_DETECTOR],
  ["weapon_revolver_navy_crossover", WEAPON_REVOLVER_NAVY_CROSSOVER],
  ["weapon_thrown_bolas_hawkmoth", WEAPON_THROWN_BOLAS_HAWKMOTH],
  ["weapon_thrown_bolas_ironspiked", WEAPON_THROWN_BOLAS_IRONSPIKED],
  ["weapon_thrown_bolas_intertwined", WEAPON_THROWN_BOLAS_INTERTWINED],
  ["weapon_melee_knife_horror", WEAPON_MELEE_KNIFE_HORROR],
  ["weapon_melee_knife_rustic", WEAPON_MELEE_KNIFE_RUSTIC],
  ["weapon_melee_lantern_halloween", WEAPON_MELEE_LANTERN_HALLOWEEN]
]);
export {
  WEAPONS_MAP,
  WEAPON_ALLIGATOR,
  WEAPON_ANIMAL,
  WEAPON_BADGER,
  WEAPON_BEAR,
  WEAPON_BEAVER,
  WEAPON_BLEEDING,
  WEAPON_BOW,
  WEAPON_BOW_CHARLES,
  WEAPON_BOW_IMPROVED,
  WEAPON_COUGAR,
  WEAPON_COYOTE,
  WEAPON_DEER,
  WEAPON_DROWNING,
  WEAPON_DROWNING_IN_VEHICLE,
  WEAPON_EXPLOSION,
  WEAPON_FALL,
  WEAPON_FIRE,
  WEAPON_FISHINGROD,
  WEAPON_FOX,
  WEAPON_HORSE,
  WEAPON_KIT_BINOCULARS,
  WEAPON_KIT_BINOCULARS_IMPROVED,
  WEAPON_KIT_CAMERA,
  WEAPON_KIT_CAMERA_ADVANCED,
  WEAPON_KIT_DETECTOR,
  WEAPON_KIT_METAL_DETECTOR,
  WEAPON_LASSO,
  WEAPON_LASSO_REINFORCED,
  WEAPON_MELEE_ANCIENT_HATCHET,
  WEAPON_MELEE_BROKEN_SWORD,
  WEAPON_MELEE_CLEAVER,
  WEAPON_MELEE_DAVY_LANTERN,
  WEAPON_MELEE_HATCHET,
  WEAPON_MELEE_HATCHET_DOUBLE_BIT,
  WEAPON_MELEE_HATCHET_DOUBLE_BIT_RUSTED,
  WEAPON_MELEE_HATCHET_HEWING,
  WEAPON_MELEE_HATCHET_HUNTER,
  WEAPON_MELEE_HATCHET_HUNTER_RUSTED,
  WEAPON_MELEE_HATCHET_MELEEONLY,
  WEAPON_MELEE_HATCHET_VIKING,
  WEAPON_MELEE_KNIFE,
  WEAPON_MELEE_KNIFE_BEAR,
  WEAPON_MELEE_KNIFE_BILL,
  WEAPON_MELEE_KNIFE_CHARLES,
  WEAPON_MELEE_KNIFE_CIVIL_WAR,
  WEAPON_MELEE_KNIFE_DUTCH,
  WEAPON_MELEE_KNIFE_HORROR,
  WEAPON_MELEE_KNIFE_HOSEA,
  WEAPON_MELEE_KNIFE_JAVIER,
  WEAPON_MELEE_KNIFE_JAWBONE,
  WEAPON_MELEE_KNIFE_JOHN,
  WEAPON_MELEE_KNIFE_KIERAN,
  WEAPON_MELEE_KNIFE_LENNY,
  WEAPON_MELEE_KNIFE_MICAH,
  WEAPON_MELEE_KNIFE_MINER,
  WEAPON_MELEE_KNIFE_RUSTIC,
  WEAPON_MELEE_KNIFE_SADIE,
  WEAPON_MELEE_KNIFE_SEAN,
  WEAPON_MELEE_KNIFE_TRADER,
  WEAPON_MELEE_KNIFE_UNCLE,
  WEAPON_MELEE_KNIFE_VAMPIRE,
  WEAPON_MELEE_LANTERN,
  WEAPON_MELEE_LANTERN_ELECTRIC,
  WEAPON_MELEE_LANTERN_HALLOWEEN,
  WEAPON_MELEE_MACHETE,
  WEAPON_MELEE_MACHETE_COLLECTOR,
  WEAPON_MELEE_MACHETE_HORROR,
  WEAPON_MELEE_TORCH,
  WEAPON_MELEE_TORCH_CROWD,
  WEAPON_MOONSHINEJUG_MP,
  WEAPON_MUSKRAT,
  WEAPON_PISTOL_M1899,
  WEAPON_PISTOL_MAUSER,
  WEAPON_PISTOL_MAUSER_DRUNK,
  WEAPON_PISTOL_SEMIAUTO,
  WEAPON_PISTOL_VOLCANIC,
  WEAPON_RACCOON,
  WEAPON_RAMMED_BY_CAR,
  WEAPON_REPEATER_CARBINE,
  WEAPON_REPEATER_CARBINE_SADIE,
  WEAPON_REPEATER_EVANS,
  WEAPON_REPEATER_HENRY,
  WEAPON_REPEATER_WINCHESTER,
  WEAPON_REPEATER_WINCHESTER_JOHN,
  WEAPON_REVOLVER_CATTLEMAN,
  WEAPON_REVOLVER_CATTLEMAN_HOSEA,
  WEAPON_REVOLVER_CATTLEMAN_HOSEA_DUALWIELD,
  WEAPON_REVOLVER_CATTLEMAN_JOHN,
  WEAPON_REVOLVER_CATTLEMAN_KIERAN,
  WEAPON_REVOLVER_CATTLEMAN_LENNY,
  WEAPON_REVOLVER_CATTLEMAN_MEXICAN,
  WEAPON_REVOLVER_CATTLEMAN_PIG,
  WEAPON_REVOLVER_CATTLEMAN_SADIE,
  WEAPON_REVOLVER_CATTLEMAN_SADIE_DUALWIELD,
  WEAPON_REVOLVER_CATTLEMAN_SEAN,
  WEAPON_REVOLVER_DOUBLEACTION,
  WEAPON_REVOLVER_DOUBLEACTION_EXOTIC,
  WEAPON_REVOLVER_DOUBLEACTION_GAMBLER,
  WEAPON_REVOLVER_DOUBLEACTION_JAVIER,
  WEAPON_REVOLVER_DOUBLEACTION_MICAH,
  WEAPON_REVOLVER_DOUBLEACTION_MICAH_DUALWIELD,
  WEAPON_REVOLVER_LEMAT,
  WEAPON_REVOLVER_NAVY,
  WEAPON_REVOLVER_NAVY_CROSSOVER,
  WEAPON_REVOLVER_SCHOFIELD,
  WEAPON_REVOLVER_SCHOFIELD_BILL,
  WEAPON_REVOLVER_SCHOFIELD_CALLOWAY,
  WEAPON_REVOLVER_SCHOFIELD_DUTCH,
  WEAPON_REVOLVER_SCHOFIELD_DUTCH_DUALWIELD,
  WEAPON_REVOLVER_SCHOFIELD_GOLDEN,
  WEAPON_REVOLVER_SCHOFIELD_UNCLE,
  WEAPON_RIFLE_BOLTACTION,
  WEAPON_RIFLE_BOLTACTION_BILL,
  WEAPON_RIFLE_ELEPHANT,
  WEAPON_RIFLE_SPRINGFIELD,
  WEAPON_RIFLE_VARMINT,
  WEAPON_RUN_OVER_BY_CAR,
  WEAPON_SHOTGUN_DOUBLEBARREL,
  WEAPON_SHOTGUN_DOUBLEBARREL_EXOTIC,
  WEAPON_SHOTGUN_DOUBLEBARREL_UNCLE,
  WEAPON_SHOTGUN_PUMP,
  WEAPON_SHOTGUN_REPEATING,
  WEAPON_SHOTGUN_SAWEDOFF,
  WEAPON_SHOTGUN_SAWEDOFF_CHARLES,
  WEAPON_SHOTGUN_SEMIAUTO,
  WEAPON_SHOTGUN_SEMIAUTO_HOSEA,
  WEAPON_SNAKE,
  WEAPON_SNIPERRIFLE_CARCANO,
  WEAPON_SNIPERRIFLE_ROLLINGBLOCK,
  WEAPON_SNIPERRIFLE_ROLLINGBLOCK_EXOTIC,
  WEAPON_SNIPERRIFLE_ROLLINGBLOCK_LENNY,
  WEAPON_THROWN_BOLAS,
  WEAPON_THROWN_BOLAS_HAWKMOTH,
  WEAPON_THROWN_BOLAS_INTERTWINED,
  WEAPON_THROWN_BOLAS_IRONSPIKED,
  WEAPON_THROWN_DYNAMITE,
  WEAPON_THROWN_MOLOTOV,
  WEAPON_THROWN_POISONBOTTLE,
  WEAPON_THROWN_THROWING_KNIVES,
  WEAPON_THROWN_THROWING_KNIVES_JAVIER,
  WEAPON_THROWN_TOMAHAWK,
  WEAPON_THROWN_TOMAHAWK_ANCIENT,
  WEAPON_UNARMED,
  WEAPON_WOLF,
  WEAPON_WOLF_MEDIUM,
  WEAPON_WOLF_SMALL
};
