name: 'Publish Package'
on:
  push:
    tags:
      - '*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - run: |
          pnpm install --frozen-lockfile
          git config --global user.name "GitHub Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          pnpm version ${{ github.ref_name }} --git-tag-version false
          pnpm run ci
          git add .
          git commit -am '${{ github.ref_name }}'
          git push

      # because we update the package version pnpm will get mad over an unclean branch
      # we don't want a bunch of version bump commits so just ignore the git checks
      - run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
